blank_isses_enabled: false
issue_templates:
  - name: Task Completed
    description: Submit a task to trigger a reward.
    title: "[TASK COMPLETED] "
    labels: ["task"]
    file: task-completed.md
u
